testpress/android-player-sdk

app/src/main/java/com/tpstream/app/PlayerActivity.kt

- When opening `PlayerActivity` from `DownloadListActivity`, the `provider` and `orgCode` were not initialized, causing the app to crash due to uninitialized lateinit properties.
- In this commit, we set default values for `provider` and `orgCode` since these parameters are not required for offline videos.

fix: Unable to Play Video from Download Activity in Sample App

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/data/Asset.kt
player/src/main/java/com/tpstream/player/data/AssetModelMapping.kt
player/src/main/java/com/tpstream/player/data/source/network/NetworkAsset.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/java/com/tpstream/player/util/NetworkClient.kt

- In this commit, we handle the 'Not Started' state for livestreams. If the livestream state is 'Not Started', we display a notice message and, in the background, make requests for the m3u8 URL at 10-second intervals until the request succeeds. Once successful, we reload the player to start the livestream.

fix: Handle Livestream Not Started State

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/data/Asset.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- In this commit, we handle the livestream disconnected state. If the livestream state is disconnected, we display a notice message and, in the background, make the asset detail API call at 15-second intervals to check for status changes in the livestream.

fix: Handle Livestream Disconnected State

---

player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt

- Previously, the player was used inside the VideoDownloadRequestCreationHandler, preventing the exposure of the download start API. In this commit, the player has been removed, and `Asset` and `TpInitParams` have been added instead.

refactor: Remove player from VideoDownloadRequestCreationHandler

---

player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- Previously, the player was used inside the DownloadResolutionSelectionSheet, preventing the exposure of the download start API. In this commit, the player has been removed, and `Asset` and `TpInitParams` have been added instead.

refactor: Remove player from DownloadResolutionSelectionSheet

---

app/src/main/java/com/tpstream/app/MainActivity.kt
app/src/main/res/layout/activity_main.xml
player/src/main/java/com/tpstream/player/constants/PlaybackError.kt
player/src/main/java/com/tpstream/player/offline/TpStreamDownloadManager.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- In this commit, we added the `startDownload()` method in `TpStreamDownloadManager`. This allows for video downloads without the player, as well as downloads with the player. Additionally, we removed the existing download logic from `TpstreamPlayerView`.

fix: Add API to start download

---

player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- In some cases, while updating the download button image, a NullPointerException occurred. In this commit, we added null checks for the `fragmentActivity`, `assetId`, and `downloadButton` to prevent this issue.

fix: NullPointerException when Updating the Download Button Image

---

player/src/main/java/com/tpstream/player/TpInitParams.kt

- In this commit, we have added Null or empty validation to `videoId`, and `accessToken` in `TpInitParams`

fix: Add Null or empty validation for videoId, and accessToken

---

player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt

- In this commit bcee6aa, we made `autoPlay` a non-nullable value and set the default to false, but it needs to be true.
- In this commit, we set `autoPlay` as default true.

 fix: Set autoPlay as default true

---

player/src/main/java/com/tpstream/player/data/Asset.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- Previously, the download button was not displayed for live streams. We have now added a check to ensure that the video object in the Asset model is not null and that the transcoding is complete. If these conditions are met, the download button will be shown.

fix: Download button not appearing for completed livestreams

---

player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/res/values/strings.xml

- In this commit, we rephrased the internet error message for renewing the playback license to enhance understanding.

refactor: Show user understandable error message

---

player/src/main/java/com/tpstream/player/offline/OfflineDRMLicenseHelper.kt
player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt

- In this commit, we replaced the `DownloadHelper` parameter with `Format` in `fetchLicense()` to improve the reusability of the `fetchLicense()` function.

refactor: Replace `DownloadHelper` parameter with `Format` in `fetchLicense()`

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/TPStreamPlayerListener.kt
player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- Previously, when fetching the asset with an invalid access token, we displayed an error message and called onPlayerError.
- In this commit, we added onAccessTokenExpired with a function type parameter. Now, if the access token is invalid, we call onAccessTokenExpired first. This allows us to obtain a new access token and reload the player. If onAccessTokenExpired is not overridden, the previous behavior will occur: we display the error and call onPlayerError with
- INVALID_ACCESS_TOKEN_FOR_ASSETS.

fix: Add onAccessTokenExpired callback in TPStreamPlayerListener

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- In this commit, we added the option to call onAccessTokenExpired when a DRM license fetching error occurs.
- If the DRM license is expired, we update the DRM license URL and play the ExoPlayer without fetching the asset.

fix: Add onAccessTokenExpired callback

---

player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/offline/OfflineDRMLicenseHelper.kt
player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/java/com/tpstream/player/util/SentryLogger.kt
player/src/main/res/values/strings.xml

- In this commit, we added the option to call onAccessTokenExpired when the offline license is expired. Once we obtain the new access token, we fetch the DRM license key, replace the existing downloaded video, and reload the player.

fix: App crash when renew offline drm licence

---

player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- In this commit, we ensure that the showErrorMessage function is called only if the fragment is added to the activity to prevent app crashes.

fix: Check if fragment is added to activity before calling showErrorMessage

---

player/src/main/java/com/tpstream/player/constants/PlaybackError.kt

- Previously, we displayed custom error codes in error messages, while Exoplayer returns numerous error codes. We only showed four types of custom error codes.
- In this commit, we changed the error messages to display the actual player error codes. This will make it easier to identify and troubleshoot issues quickly.

fix: Display Player error code instead of custom codes

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/util/SentryLogger.kt

- In this commit, we added the userId field in `TpInitParams` and also included it as a Sentry tag. This will help us identify specific user issues more effectively.

fix: Add userId field in TpInitParams

---

player/build.gradle
player/src/main/java/com/tpstream/player/util/SentryLogger.kt

- In this commit, we included the player SDK version in the Sentry log using the `TPStreamsAndroidPlayerSDKVersion` tag.

fix: Add player SDK version in Sentry log

---

player/src/main/java/com/tpstream/player/util/SentryLogger.kt

- In this commit, we introduced a custom object in Sentry to capture the following data: SDK Version, Player ID, Error Type, Error Code, Error Message, Org Code, Video ID, AccessToken, and userId.

fix: Add custom object in Sentry

---

player/src/main/java/com/tpstream/player/TPStreamSDK.kt
player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/offline/OfflineDRMLicenseHelper.kt
player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt

- Previously, we added rental_duration_seconds, but it was not effective according to Widevine policy. Rental duration is the total duration of license activation and usage before expiration. However, we also need to provide the license duration separately. By default, the license duration was 8 hours, so even if we set the rental duration to 15 days, the license would expire in 8 hours. In this commit, we added the license_duration_seconds query parameter to set both rental and license durations to the same value. The default value in the Android SDK is now set to 15 days.

fix: Add license_duration_seconds in DRM license URL query parameter

---

player/src/main/java/com/tpstream/player/TPStreamPlayerListener.kt

- Removed the default implementation of the `onAccessTokenExpired` method from the `TPStreamPlayerListener` interface.
- This change ensures that implementing classes must provide their own implementation for handling access token expiration, improving code clarity, and enforcing explicit behavior management.

fix: Remove default implementation of `onAccessTokenExpired` in `TPStreamPlayerListener`

---

player/src/main/java/com/tpstream/player/ui/AdvancedResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- Previously, we displayed the resolution list using the custom `TrackInfo` class with formats, but we couldn't identify the selected resolution initially, which prevented us from showing the selected resolution on first load.
- In this commit, we've added an `isSelected` field in the `TrackInfo` class to return a boolean indicating whether the track is selected.
- Additionally, we refactored the code by extracting the override creation from `AdvancedResolutionSelectionSheet`. Now, we only return the track index to `TPStreamsPlayerView` when a resolution is selected. The override is then created and applied to the player using the index.

refactor: Improve AdvancedResolutionSelectionSheet for better resolution selection

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/TpInitParams.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- In this commit, we added a feature to specify the initial video resolution through the parameters. This enhancement allows us to remember and restore the user's last video resolution state.

enhancement: Add option to set initial video resolution in parameters

---

player/src/main/java/com/tpstream/player/TPStreamSDK.kt
player/src/main/java/com/tpstream/player/util/SentryLogger.kt

- In this commit, we included the TPStreamsSDK provider in the Sentry log using the `Provider` tag.

fix: Add TPStreamsSDK provider in Sentry log

---

player/src/main/java/com/tpstream/player/data/Asset.kt
player/src/main/java/com/tpstream/player/data/AssetModelMapping.kt
player/src/main/java/com/tpstream/player/data/source/network/NetworkAsset.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- In this commit, we added the `isDrmProtected` field to the `Asset.Video` model, which was previously missing. This field allows us to identify whether a video is DRM-protected. For online playback, this value is obtained from the network. For offline playback, DRM protection is determined by checking if the playback URL ends with `.mpd`.
- Additionally, we updated the `enable_drm` field in NetworkAsset to `isDrmProtected`.

fix: Add `isDrmProtected` field to Asset.Video Model

---

player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt

- Ensure player parameters are properly initialized before checking download conditions to prevent crashes in edge cases. Added `isParamsInitialized()` validation before displaying the download button.

fix: Add param initialization check to prevent crash

---

player/src/main/java/com/tpstream/player/Mapping.kt
player/src/main/java/com/tpstream/player/constants/PlaybackSpeed.kt
player/src/main/java/com/tpstream/player/ui/PlaybackSpeedPopupWindow.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/java/com/tpstream/player/ui/adapter/PlaybackSpeedAdapter.kt
player/src/main/player-mapping-files/kotlin/ExoPlayer2Mapping.kt
player/src/main/player-mapping-files/kotlin/Media3PlayerMapping.kt
player/src/main/player-mapping-files/layout/exo_player2_control_view.xml
player/src/main/player-mapping-files/layout/media3_player_control_view.xml
player/src/main/res/layout/exo_player_control_view.xml
player/src/main/res/layout/playback_speed_list_item.xml
player/src/main/res/layout/popup_window_layout.xml

- In this commit, we added a custom playback speed option to the player view, including 1.75x speed, which was missing from the default ExoPlayer speeds.
- The existing playback speed selector from ExoPlayer has been disabled, and the custom speed options now provide more flexibility, including the `1.75x` speed setting.

enhancement: Add 1.75x playback speed in player

---

player/src/main/java/com/tpstream/player/util/DeviceUtil.kt

- The `MediaCodecList` may contain duplicate entries for the same underlying codec represented by alternate codec names (aliases). In this commit, we filter the codec list using the isAlias method from MediaCodecInfo for Android SDK level 29 (Q) and above. We retain all codecs for lower versions since `MediaCodecList` does not return duplicates.

fix: Filter duplicate codecs in the available codec list

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt
player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- In this commit, we added a manual option to secure the view for L3 devices, as users on such devices can take screenshots or record the screen during DRM playback.
- By adding this feature, users will no longer be able to capture screenshots or screen recordings while DRM-protected content is being played.

fix: Secure screen for L3 devices during DRM video playback

---

player/src/main/java/com/tpstream/player/Mapping.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt
player/src/main/player-mapping-files/kotlin/ExoPlayer2Mapping.kt
player/src/main/player-mapping-files/kotlin/Media3PlayerMapping.kt

- Previously, ExoPlayer selected the resolution based on internet speed, sometimes opting for a higher resolution than desired. This commit introduces a DefaultBandwidthMeter with an initial bitrate of 200 kbps, ensuring that ExoPlayer initially selects a track around this bitrate, which corresponds to a low resolution. The resolution will then adapt based on the actual internet speed.

fix: Add BandwidthMeter to ExoPlayer for improved initial video resolution selection

---

player/src/main/java/com/tpstream/player/TpStreamPlayer.kt

- This update introduces a new method, `getRenderersFactory()`, in the TpStreamPlayerImpl class to create a `DefaultRenderersFactory` with decoder fallback enabled. This enhancement is integrated into the `ExoPlayer` initialization, improving playback reliability by allowing the player to switch to alternative decoders when necessary

fix: Add Custom Renderers Factory with Decoder Fallback to ExoPlayer

---

player/src/main/java/com/tpstream/player/Mapping.kt
player/src/main/java/com/tpstream/player/TpStreamPlayer.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/player-mapping-files/kotlin/ExoPlayer2Mapping.kt
player/src/main/player-mapping-files/kotlin/Media3PlayerMapping.kt

- This update introduces a `useSoftwareDecoder` flag in `TpStreamPlayerImpl` to allow for software decoding during ExoPlayer initialization. The `init()` method is modified to accept this flag, and the `getRenderersFactory()` method configures a custom `MediaCodecSelector` to filter for software-only codecs when enabled. Additionally, `TpStreamPlayerFragment` is updated to pass this option during player setup, enhancing playback flexibility across devices.

fix: Add option to enable Software Decoding

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/tpstream/app/MainActivity.kt

- Updated the target and compile SDK version from 33 to 34 in the app module.
Added runtime permission request for push notifications for Android 13 and above to comply with new requirements.

fix: Update Target SDK version in app module

---

player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt

- In this commit, we calculate the sizes of both the selected audio and video tracks to display the correct total size in the download bottom sheet.
- Previously, we only showed the size of the video track, which led to inaccurate size representation.

fix: Incorrect video size in Download resolution sheet

---

player/src/main/java/com/tpstream/player/data/Asset.kt
player/src/main/java/com/tpstream/player/data/AssetModelMapping.kt
player/src/main/java/com/tpstream/player/data/source/network/TPStreamsNetworkAsset.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt
player/src/test/java/com/tpstream/player/AssetModelMappingTest.kt
player/src/test/java/com/tpstream/player/TPStreamsNetworkAssetTest.kt

- Updated the `TpstreamNetworkAsset` and `Asset` models to handle playlist data from the API response.
- If the API does not provide the size, the existing fallback method using bitrate and duration will be applied, although it may be less accurate.

fix: Show download media size from API response

---

player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/util/DeviceUtil.kt

- Previously, the codec selection logic for DRM-protected content on L3 devices was incorrect due to the unavailability of secure codecs.
- In this commit, we improve the codec selection logic to prioritize secure codecs for DRM content, but if none are available, it falls back to non-secure codecs. For non-DRM content, it directly chooses the best non-secure codec based on resolution support.

fix: Codec Selection for L3 Devices in DownloadResolutionSelectionSheet

---

player/src/main/java/com/tpstream/player/TpStreamPlayer.kt

- Enabled the ExoPlayer enhancement that adds additional threads for decoding video content on older devices. This option, which is enabled by default on Android 12 and above, ensures smoother playback of DRM-protected content at 2x speed. Enabling this feature prevents video stuttering and frame drops on devices with lower specifications.
- For more details, refer to [ExoPlayer issue #11209](https://github.com/google/ExoPlayer/issues/11209) and the [Android Media3 ExoPlayer customization guide](https://developer.android.com/media/media3/exoplayer/customization#enabling-asynchronous-buffer-queueing).

fix: Video shuttering issue while playing DRM content at 2x speed

---

player/src/main/java/com/tpstream/player/constants/PlaybackError.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt
player/src/main/res/layout/fragment_tp_stream_player.xml

- Previously, we displayed a generic error message for ExoPlayer error code 4001. This error typically occurs due to insufficient system resources, missing or incompatible decoder libraries, or similar issues. Restarting the device usually resolves it.
- We added a custom error message specifically for error code 4001.
- Included a troubleshooting link within the message for further assistance.

fix: Display custom message for Error code 4001

---

player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- Resolved an issue where API call counters (`offlineLicenseApiCallCount` and `assetApiCallCount`) were not reset after a successful license fetch or player preparation.
- Previously, this caused an authentication failure loop even when a valid access token was provided after an initial failure. Now, the counters reset correctly, enabling proper reauthentication and playback reinitialization when the app is reopened or a new access token is passed.

fix: Reset API call counters to prevent authentication loop

---

player/src/main/java/com/tpstream/player/TPStreamPlayerListener.kt

- Added `@Deprecated` annotations to functions in `TPStreamPlayerListener` that expose `ExoPlayer` objects (`DeviceInfo`, `VideoSize`, `PlayerPositionInfo`, and `Timeline`).
- Since our SDK wraps ExoPlayer, directly exposing its objects can lead to build issues for users who may not have the correct ExoPlayer dependencies. Deprecating these functions ensures better compatibility and prevents unintended dependency issues.
- Moving forward, we should introduce alternative methods that abstract ExoPlayer-specific types to maintain SDK independence.

fix: Mark functions exposing ExoPlayer objects as deprecated

---

player/src/main/java/com/tpstream/player/ui/AdvancedResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt
player/src/main/java/com/tpstream/player/ui/SimpleResolutionSelectionSheet.kt
player/src/main/res/values-night/styles.xml
player/src/main/res/values/styles.xml

- When using the Android player SDK in Flutter and React Native via native bindings, the bottom sheet theme was sometimes overridden by the host app’s theme. This caused UI inconsistencies, especially in dark mode, where text became unreadable.
- To resolve this, all bottom sheets (`AdvancedResolutionSelectionSheet`, `DownloadResolutionSelectionSheet`, and `SimpleResolutionSelectionSheet`) now explicitly use `CustomBottomSheetDialogTheme`. This ensures a consistent appearance across all platforms, preventing theme conflicts in different integrations.

fix: Ensure consistent bottom sheet theme across all platforms

---

player/src/main/player-mapping-files/layout/exo_player2_control_view.xml
player/src/main/player-mapping-files/layout/media3_player_control_view.xml
player/src/main/res/layout/exo_player_control_view.xml

- When the user sets the screen size to large, all UI elements scale up, reducing available space in the player controls. This causes ExoPlayer to switch to minimal mode, hiding the next/previous track buttons.
- Since ExoPlayer currently doesn’t provide an option to control minimal mode externally, this update reduces the bottom bar height to `50dp` and the progress bar margin to `42dp`. This ensures that all controls remain visible even on large screen sizes.
- Once ExoPlayer allows explicit control over minimal mode, we will replace this workaround accordingly.

fix: Adjust bottom bar height to prevent ExoPlayer minimal mode

---

player/src/main/java/com/tpstream/player/ui/TPStreamPlayerView.kt
player/src/main/java/com/tpstream/player/ui/TpStreamPlayerFragment.kt

- Previously, when releasing the player in onPause or onStop, playerView.player was not explicitly set to null. As a result, when the app resumed, a new player instance was created and assigned to playerView, but the old reference remained. This occasionally led to unpredictable behavior, including random 4003 errors.
- This fix ensures that playerView.player is set to null before assigning a new player instance, preventing conflicts and ensuring a clean player reinitialization process.

fix: Properly detach player when releasing

---

app/src/main/java/com/tpstream/app/PlayerActivity.kt
player/src/main/java/com/tpstream/player/offline/OfflineDRMLicenseHelper.kt
player/src/main/java/com/tpstream/player/offline/TpStreamDownloadManager.kt
player/src/main/java/com/tpstream/player/offline/VideoDownloadRequestCreationHandler.kt
player/src/main/java/com/tpstream/player/ui/DownloadResolutionSelectionSheet.kt

- Added a callback mechanism (OnAccessTokenExpiredListener) to request a new access token when the DRM license fetch fails with a 401 error.
- Updated OfflineDRMLicenseHelper to detect DRM authentication errors.
- Integrated token refresh handling in TpStreamDownloadManager and DownloadResolutionSelectionSheet.
- Implemented retry logic in VideoDownloadRequestCreationHandler, allowing up to 3 retries with a new token before failing.
- If all retries fail, the user sees an error message indicating that the video download cannot proceed due to a license issue.

fix: Unable to download the DRM video with single accessToken

---

.github/workflows/test-runner.yml

- Updated GitHub Actions workflow to use JDK 17.
- Ensures compatibility with AGP 8+ and modern Gradle builds.

chore: Update GitHub Actions to use JDK 17

---

player/build.gradle

- Upgraded Sentry Android SDK from 6.4.2 → 7.20.0
- The older Sentry version packaged native `.so` binaries aligned to 4KB pages.
- Google Play now requires all apps to support devices with 16KB page sizes.
- The new Sentry release includes updated native libraries aligned to 16KB,
ensuring compatibility with upcoming Android devices and Play Store policies.

chore: Update Sentry Android SDK to version 7.20.0
